Feature mixedfxhum
LamaDiLuce/polaris-opencore pull request #82
Opened 2023-06-25 08:50 UTC by f4iey

This features allows clash sounds to be mixed with the hum, so it does not starts over every time we clash.

Instead of stopping the hum sound, the channel gain is set to 0, so we can hear the clash sound properly before getting back to maximum volume.

For complex ~~meme~~ fonts, it allows a smoother and better sound experience overall

2023-07-24 21:55 UTC, FarFlyer requested changes
I like the idea to have the hum constantly playing and it's also easier to add custom clashes. I guess that many sound fonts were originally made to be used with just one single audio channel, but having more channels it makes a lot of sense to keep playing the hum and add the clash on top.

2023-07-24 21:55 UTC, FarFlyer commented on libraries/CoreAudio/CoreAudio.h
> +#define ATT 0.5
please define it as private `static constexpr float` and change the name to a full word for clarity

2023-07-24 21:55 UTC, FarFlyer commented on libraries/CoreAudio/CoreAudio.cpp
> +            //soundPlayFlashRaw.stop();
please remove the commented line. It's fine to have the previous version in the history and a cleaner code

2023-07-24 21:55 UTC, FarFlyer commented on libraries/CoreAudio/CoreAudio.cpp
> +            // soundPlayFlashRaw.stop();
please remove the commented line. It's fine to have the previous version in the history and a cleaner code

2023-07-24 21:55 UTC, FarFlyer commented on libraries/CoreAudio/CoreAudio.cpp
> +        //soundPlayFlashRaw.stop();
please remove the commented line. It's fine to have the previous version in the history and a cleaner code

2023-07-25 07:38 UTC, f4iey reviewed
Comments are removed and the attenuation rate is now a `private static constexpr float` named `ATTENUATION_RATE` for more clarity.

2023-07-25 20:17 UTC, FarFlyer approved these changes

2023-07-25 20:17 UTC, merged